log_file = "/var/log/mdsbom.log"
database_url = "file:///var/lib/mdsbom/mdsbom.db?mode=rwc&connection_limit=1"
api_server_address = "127.0.0.1:5236"
api_internal_socket_path = "/run/mdsbom_api.sock"
api_internal_socket_owner = "root:mdsbom"
api_internal_socket_mode = "660"
rpc_socket_path = "/run/mdsbom_rpc.sock"
rpc_socket_owner = "root:mdsbom"
rpc_socket_mode = "660"

