services:
  api:
    build: ./api
    image: "ghcr.io/forallsecure-customersolutions/mayhem-demo/api:${SHA:-latest}"
    volumes:
      - ./coverage:/app/coverage
    ports:
      - "8000:8000"
    depends_on:
      - redis

  ui:
    build: ./ui
    image: "ghcr.io/forallsecure-customersolutions/mayhem-demo/ui:${SHA:-latest}"
    ports:
      - "3000:3000"
    depends_on:
      - api

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  car:
    platform: linux/amd64
    build: ./car
    image: "ghcr.io/forallsecure-customersolutions/mayhem-demo/car:${SHA:-latest}"
    command: "/app/src/wait-for-it.sh api -- make upload"
    depends_on:
      - api
