name: Mayhem CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      mayhem_url:
        description: 'Mayhem URL'
        required: true
        default: 'https://app.mayhem.security'
        type: string
      workspace:
        description: 'Mayhem Workspace'
        required: true
        default: 'platform-demo'
        type: string
    secrets:
      mayhem-token:
        description: 'Mayhem Token'
        required: false

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set Mayhem token
        shell: pwsh
        run: |
          if ("${{ secrets.mayhem-token }}" -ne "") {
            Write-Host "::add-mask::${{ secrets.mayhem-token }}"
            echo "MAYHEM_TOKEN=${{ secrets.mayhem-token }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          }

      - name: Set default inputs if not provided
        shell: pwsh
        run: |
          echo "MAYHEM_URL=${{ inputs.mayhem_url }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "WORKSPACE=${{ inputs.workspace }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Download and install Mayhem CLI
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://app.mayhem.security/cli/Windows/mayhem.msi" -OutFile "mayhem.msi"
          Start-Process msiexec.exe -ArgumentList "/i mayhem.msi /quiet /norestart" -Wait
          # Add Mayhem CLI to PATH
          $mayhemPath = "C:\Program Files\ForAllSecure\Mayhem\bin"
          [System.Environment]::SetEnvironmentVariable('PATH', "$env:PATH;$mayhemPath", [System.EnvironmentVariableTarget]::Process)
          Write-Host "Mayhem CLI installed successfully"

      - name: Authenticate Mayhem CLI
        shell: pwsh
        run: |
          if (-not $env:MAYHEM_TOKEN) {
            Write-Error "Mayhem token not set"
            exit 1
          }
          mayhem login $env:MAYHEM_URL $env:MAYHEM_TOKEN

      - name: Set up MSBuild environment and build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd cli
          msbuild geofencing.sln

      - name: Package the executable for Mayhem
        shell: pwsh
        run: |
          $packageDir = "cli/package"
          $exePath = "cli/x64/Debug/geofencing.exe"
          if (-Not (Test-Path $exePath)) {
            Write-Error "Executable not found at $exePath"
            exit 1
          }
          mayhem package $exePath -o $packageDir

          # Ensure the package/testsuite directory exists
          $testSuiteDir = "$packageDir/testsuite"
          if (-Not (Test-Path $testSuiteDir)) {
            New-Item -ItemType Directory -Path $testSuiteDir
          }

          # Copy test files
          if (Test-Path "cli/testsuite") {
            Copy-Item -Path "cli/testsuite/*" -Destination $testSuiteDir -Recurse
          } else {
            Write-Host "No testsuite directory found."
          }

      - name: Run Mayhem
        shell: pwsh
        run: |
          mayhem run cli/package --owner $env:WORKSPACE --project mayhem-demo --target cli
