name: Mayhem CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      mayhem_url:
        description: 'Mayhem URL'
        required: true
        default: 'https://app.mayhem.security'
        type: string
      workspace:
        description: 'Mayhem Workspace'
        required: true
        default: 'platform-demo'
        type: string
    secrets:
      mayhem-token:
        description: 'Mayhem Token'
        required: false

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Step 2: Set Mayhem token using PowerShell syntax
    - name: Set Mayhem token
      shell: pwsh
      run: |
        if ($env:mayhem_token -ne "") {
          Write-Host "::add-mask::$env:mayhem_token"
          echo "MAYHEM_TOKEN=$env:mayhem_token" >> $env:GITHUB_ENV
        } elseif ($env:MAYHEM_TOKEN -ne "") {
          Write-Host "::add-mask::$env:MAYHEM_TOKEN"
          echo "MAYHEM_TOKEN=$env:MAYHEM_TOKEN" >> $env:GITHUB_ENV
        }

    # Step 3: Set default inputs if not provided
    - name: Set default inputs if not provided
      shell: pwsh
      run: |
        echo "MAYHEM_URL=${{ inputs.mayhem_url }}" >> $env:GITHUB_ENV
        echo "WORKSPACE=${{ inputs.workspace }}" >> $env:GITHUB_ENV

    # Step 4: Lowercase github.repository
    - name: Lowercase GitHub repository
      shell: pwsh
      run: |
        $repoName = $env:GITHUB_REPOSITORY.ToLower()
        echo "REPO_NAME=$repoName" >> $env:GITHUB_ENV


    # Set up MSBuild environment and run PowerShell script
    - name: Build with MSBuild using PowerShell script
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        pwsh ./cli/run_mcode.ps1
